[
  {
    "command": "apt-get update",
    "success": true,
    "stdout": "Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]\nGet:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]\nGet:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]\nGet:4 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [5103 kB]\nGet:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]\nGet:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3207 kB]\nGet:7 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]\nGet:8 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1270 kB]\nGet:9 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [48.5 kB]\nGet:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]\nGet:11 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]\nGet:12 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]\nGet:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [5290 kB]\nGet:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3518 kB]\nGet:15 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [75.9 kB]\nGet:16 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1575 kB]\nGet:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.2 kB]\nGet:18 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [83.2 kB]\nFetched 40.6 MB in 23s (1754 kB/s)\nReading package lists...\n",
    "stderr": "",
    "execution_time": 23.983294248580933
  },
  {
    "command": "apt-get install -y python3.10-dev",
    "success": true,
    "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following additional packages will be installed:\n  libexpat1-dev libpython3.10 libpython3.10-dev zlib1g-dev\nThe following NEW packages will be installed:\n  libexpat1-dev libpython3.10 libpython3.10-dev python3.10-dev zlib1g-dev\n0 upgraded, 5 newly installed, 0 to remove and 8 not upgraded.\nNeed to get 7532 kB of archives.\nAfter this operation, 28.9 MB of additional disk space will be used.\nGet:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libexpat1-dev amd64 2.4.7-1ubuntu0.6 [148 kB]\nGet:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10 amd64 3.10.12-1~22.04.10 [1950 kB]\nGet:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-2ubuntu9.2 [164 kB]\nGet:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpython3.10-dev amd64 3.10.12-1~22.04.10 [4763 kB]\nGet:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3.10-dev amd64 3.10.12-1~22.04.10 [508 kB]\nFetched 7532 kB in 9s (827 kB/s)\nSelecting previously unselected package libexpat1-dev:amd64.\n(Reading database ... \n(Reading database ... 5%\n(Reading database ... 10%\n(Reading database ... 15%\n(Reading database ... 20%\n(Reading database ... 25%\n(Reading database ... 30%\n(Reading database ... 35%\n(Reading database ... 40%\n(Reading database ... 45%\n(Reading database ... 50%\n(Reading database ... 55%\n(Reading database ... 60%\n(Reading database ... 65%\n(Reading database ... 70%\n(Reading database ... 75%\n(Reading database ... 80%\n(Reading database ... 85%\n(Reading database ... 90%\n(Reading database ... 95%\n(Reading database ... 100%\n(Reading database ... 13507 files and directories currently installed.)\nPreparing to unpack .../libexpat1-dev_2.4.7-1ubuntu0.6_amd64.deb ...\nUnpacking libexpat1-dev:amd64 (2.4.7-1ubuntu0.6) ...\nSelecting previously unselected package libpython3.10:amd64.\nPreparing to unpack .../libpython3.10_3.10.12-1~22.04.10_amd64.deb ...\nUnpacking libpython3.10:amd64 (3.10.12-1~22.04.10) ...\nSelecting previously unselected package zlib1g-dev:amd64.\nPreparing to unpack .../zlib1g-dev_1%3a1.2.11.dfsg-2ubuntu9.2_amd64.deb ...\nUnpacking zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu9.2) ...\nSelecting previously unselected package libpython3.10-dev:amd64.\nPreparing to unpack .../libpython3.10-dev_3.10.12-1~22.04.10_amd64.deb ...\nUnpacking libpython3.10-dev:amd64 (3.10.12-1~22.04.10) ...\nSelecting previously unselected package python3.10-dev.\nPreparing to unpack .../python3.10-dev_3.10.12-1~22.04.10_amd64.deb ...\nUnpacking python3.10-dev (3.10.12-1~22.04.10) ...\nSetting up libpython3.10:amd64 (3.10.12-1~22.04.10) ...\nSetting up libexpat1-dev:amd64 (2.4.7-1ubuntu0.6) ...\nSetting up zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu9.2) ...\nSetting up libpython3.10-dev:amd64 (3.10.12-1~22.04.10) ...\nSetting up python3.10-dev (3.10.12-1~22.04.10) ...\nProcessing triggers for libc-bin (2.35-0ubuntu3.10) ...\n",
    "stderr": "debconf: delaying package configuration, since apt-utils is not installed\n",
    "execution_time": 11.002757549285889
  },
  {
    "command": "pip install .",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nProcessing /app/repo_to_process\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Preparing metadata (pyproject.toml): started\n  Preparing metadata (pyproject.toml): finished with status 'done'\nRequirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from mahotas==1.4.18) (2.2.6)\nBuilding wheels for collected packages: mahotas\n  Building wheel for mahotas (pyproject.toml): started\n  Building wheel for mahotas (pyproject.toml): finished with status 'done'\n  Created wheel for mahotas: filename=mahotas-1.4.18-cp310-cp310-linux_x86_64.whl size=5157338 sha256=322bfa38f41c5882fb8fca4ecae076c80309f26c4afc919baff88690c303595d\n  Stored in directory: /tmp/pip-ephem-wheel-cache-x11hqyp6/wheels/a8/f2/cc/1e92c02a4656168a595624aed18c7a028fd983fe702bc050f2\nSuccessfully built mahotas\nInstalling collected packages: mahotas\nSuccessfully installed mahotas-1.4.18\n",
    "stderr": "WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 44.01534557342529
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "============================= test session starts ==============================\nplatform linux -- Python 3.10.12, pytest-8.1.1, pluggy-1.6.0\nrootdir: /app/repo_to_process\nconfigfile: pyproject.toml\ncollected 98 items / 29 errors\n\n==================================== ERRORS ====================================\n_________________ ERROR collecting mahotas/tests/test_bbox.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_bbox.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_bbox.py:4: in <module>\n    from mahotas import bbox\nmahotas/bbox.py:8: in <module>\n    from . import _bbox\nE   ImportError: cannot import name '_bbox' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n------------------------------- Captured stderr --------------------------------\nCould not import submodules (exact error was: cannot import name '_bbox' from partially initialized module 'mahotas' (most likely due to a circular import) (/app/repo_to_process/mahotas/__init__.py)).\n\nThere are many reasons for this error the most common one is that you have\neither not built the packages or have built (using `python setup.py build`) or\ninstalled them (using `python setup.py install`) and then proceeded to test\nmahotas **without changing the current directory**.\n\nTry installing and then changing to another directory before importing mahotas.\n________________ ERROR collecting mahotas/tests/test_bwperim.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_bwperim.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_bwperim.py:1: in <module>\n    from mahotas import bwperim\nmahotas/bwperim.py:14: in <module>\n    from .labeled import bwperim\nmahotas/labeled.py:8: in <module>\n    from .morph import get_structuring_elem\nmahotas/morph.py:10: in <module>\n    from . import _morph\nE   ImportError: cannot import name '_morph' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n____________ ERROR collecting mahotas/tests/test_center_of_mass.py _____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_center_of_mass.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_center_of_mass.py:3: in <module>\n    import mahotas.center_of_mass\nmahotas/center_of_mass.py:7: in <module>\n    from . import _center_of_mass\nE   ImportError: cannot import name '_center_of_mass' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_convolve.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_convolve.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_convolve.py:3: in <module>\n    import mahotas.convolve\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_distance.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_distance.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_distance.py:1: in <module>\n    from mahotas import distance\nmahotas/distance.py:6: in <module>\n    from . import _distance\nE   ImportError: cannot import name '_distance' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_edge.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_edge.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_edge.py:1: in <module>\n    from mahotas.edge import sobel\nmahotas/edge.py:9: in <module>\n    from . import convolve, gaussian_filter\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_euler.py _________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_euler.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_euler.py:2: in <module>\n    from mahotas.euler import euler, _euler_lookup4, _euler_lookup8\nmahotas/euler.py:6: in <module>\n    from .convolve import convolve\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n____________ ERROR collecting mahotas/tests/test_features_shape.py _____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_features_shape.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_features_shape.py:1: in <module>\n    import mahotas.features.shape\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_gvoronoi.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_gvoronoi.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_gvoronoi.py:2: in <module>\n    from mahotas.segmentation import gvoronoi\nmahotas/segmentation.py:12: in <module>\n    from . import _distance\nE   ImportError: cannot import name '_distance' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_histogram.py _______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_histogram.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_histogram.py:2: in <module>\n    from mahotas.histogram import fullhistogram\nmahotas/histogram.py:34: in <module>\n    from . import _histogram\nE   ImportError: cannot import name '_histogram' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_imresize.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_imresize.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_imresize.py:2: in <module>\n    from mahotas import imresize\nE   ImportError: cannot import name 'imresize' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n______________ ERROR collecting mahotas/tests/test_interpolate.py ______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_interpolate.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_interpolate.py:1: in <module>\n    from mahotas import interpolate\nmahotas/interpolate.py:41: in <module>\n    from . import _interpolate\nE   ImportError: cannot import name '_interpolate' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_label.py _________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_label.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_label.py:1: in <module>\n    from mahotas import label\nE   ImportError: cannot import name 'label' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_labeled.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_labeled.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_labeled.py:3: in <module>\n    import mahotas.labeled\nmahotas/labeled.py:8: in <module>\n    from .morph import get_structuring_elem\nmahotas/morph.py:10: in <module>\n    from . import _morph\nE   ImportError: cannot import name '_morph' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n__________________ ERROR collecting mahotas/tests/test_lbp.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_lbp.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_lbp.py:2: in <module>\n    from mahotas.features import _lbp\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n_______________ ERROR collecting mahotas/tests/test_majority.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_majority.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_majority.py:2: in <module>\n    import mahotas.morph\nmahotas/morph.py:10: in <module>\n    from . import _morph\nE   ImportError: cannot import name '_morph' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n______________ ERROR collecting mahotas/tests/test_mean_filter.py ______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_mean_filter.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_mean_filter.py:3: in <module>\n    from mahotas.convolve import mean_filter\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_____________ ERROR collecting mahotas/tests/test_median_filter.py _____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_median_filter.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_median_filter.py:2: in <module>\n    from mahotas.convolve import median_filter, rank_filter\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_moments.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_moments.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_moments.py:3: in <module>\n    from mahotas.features.moments import moments\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_morph.py _________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_morph.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_morph.py:3: in <module>\n    from mahotas.morph import get_structuring_elem, subm, tophat_open, tophat_close\nmahotas/morph.py:10: in <module>\n    from . import _morph\nE   ImportError: cannot import name '_morph' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_polygon.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_polygon.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_polygon.py:3: in <module>\n    import mahotas.polygon\nmahotas/polygon.py:8: in <module>\n    from . import _convex\nE   ImportError: cannot import name '_convex' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_____________ ERROR collecting mahotas/tests/test_segmentation.py ______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_segmentation.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_segmentation.py:1: in <module>\n    import mahotas.segmentation\nmahotas/segmentation.py:12: in <module>\n    from . import _distance\nE   ImportError: cannot import name '_distance' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n_________________ ERROR collecting mahotas/tests/test_surf.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_surf.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_surf.py:3: in <module>\n    import mahotas.features.surf as surf\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n____________ ERROR collecting mahotas/tests/test_surf_regression.py ____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_surf_regression.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_surf_regression.py:3: in <module>\n    from mahotas.features.surf import surf\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n__________________ ERROR collecting mahotas/tests/test_tas.py __________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_tas.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_tas.py:2: in <module>\n    from mahotas.features import tas, pftas\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n____________ ERROR collecting mahotas/tests/test_template_match.py _____________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_template_match.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_template_match.py:2: in <module>\n    import mahotas.convolve\nmahotas/convolve.py:8: in <module>\n    from . import _convolve\nE   ImportError: cannot import name '_convolve' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_texture.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_texture.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_texture.py:2: in <module>\n    from mahotas.features import texture\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n_____________ ERROR collecting mahotas/tests/test_thresholding.py ______________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_thresholding.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_thresholding.py:5: in <module>\n    from mahotas.thresholding import otsu, rc, bernsen, gbernsen\nmahotas/thresholding.py:46: in <module>\n    from .histogram import fullhistogram\nmahotas/histogram.py:34: in <module>\n    from . import _histogram\nE   ImportError: cannot import name '_histogram' from 'mahotas' (/app/repo_to_process/mahotas/__init__.py)\n________________ ERROR collecting mahotas/tests/test_zernike.py ________________\nImportError while importing test module '/app/repo_to_process/mahotas/tests/test_zernike.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n/usr/lib/python3.10/importlib/__init__.py:126: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nmahotas/tests/test_zernike.py:2: in <module>\n    from mahotas.features import zernike_moments\nmahotas/features/__init__.py:6: in <module>\n    from .texture import haralick\nmahotas/features/texture.py:8: in <module>\n    from . import _texture\nE   ImportError: cannot import name '_texture' from partially initialized module 'mahotas.features' (most likely due to a circular import) (/app/repo_to_process/mahotas/features/__init__.py)\n=============================== warnings summary ===============================\nmahotas/bwperim.py:7\n  /app/repo_to_process/mahotas/bwperim.py:7: DeprecationWarning: Use\n  \n  from mahotas.labeled import bwperim\n  \n    warnings.warn(\n\n-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html\n=========================== short test summary info ============================\nERROR mahotas/tests/test_bbox.py\nERROR mahotas/tests/test_bwperim.py\nERROR mahotas/tests/test_center_of_mass.py\nERROR mahotas/tests/test_convolve.py\nERROR mahotas/tests/test_distance.py\nERROR mahotas/tests/test_edge.py\nERROR mahotas/tests/test_euler.py\nERROR mahotas/tests/test_features_shape.py\nERROR mahotas/tests/test_gvoronoi.py\nERROR mahotas/tests/test_histogram.py\nERROR mahotas/tests/test_imresize.py\nERROR mahotas/tests/test_interpolate.py\nERROR mahotas/tests/test_label.py\nERROR mahotas/tests/test_labeled.py\nERROR mahotas/tests/test_lbp.py\nERROR mahotas/tests/test_majority.py\nERROR mahotas/tests/test_mean_filter.py\nERROR mahotas/tests/test_median_filter.py\nERROR mahotas/tests/test_moments.py\nERROR mahotas/tests/test_morph.py\nERROR mahotas/tests/test_polygon.py\nERROR mahotas/tests/test_segmentation.py\nERROR mahotas/tests/test_surf.py\nERROR mahotas/tests/test_surf_regression.py\nERROR mahotas/tests/test_tas.py\nERROR mahotas/tests/test_template_match.py\nERROR mahotas/tests/test_texture.py\nERROR mahotas/tests/test_thresholding.py\nERROR mahotas/tests/test_zernike.py\n!!!!!!!!!!!!!!!!!!! Interrupted: 29 errors during collection !!!!!!!!!!!!!!!!!!!\n======================== 1 warning, 29 errors in 0.66s =========================\n",
    "stderr": "",
    "execution_time": 0.8533046245574951
  }
]