[
  {
    "command": "git submodule update --init",
    "success": true,
    "stdout": "Submodule path 'third_party/cccl': checked out '3a388b7b01512d48474b98389a3e776c8d8f817a'\nSubmodule path 'third_party/dlpack': checked out 'cd0d5e4ff888b388aef4f9b6bd5d9aa5737a020e'\nSubmodule path 'third_party/jitify': checked out '1a0ca0e837405506f3b8f7883bacb71c20d86d96'\nSubmodule path 'third_party/xsf': checked out 'f8218dab76a84b4a3fec35db4b6de0f9903438c8'\n",
    "stderr": "Submodule 'third_party/cccl' (https://github.com/NVIDIA/cccl.git) registered for path 'third_party/cccl'\nSubmodule 'third_party/dlpack' (https://github.com/dmlc/dlpack.git) registered for path 'third_party/dlpack'\nSubmodule 'third_party/jitify' (https://github.com/NVIDIA/jitify.git) registered for path 'third_party/jitify'\nSubmodule 'third_party/xsf' (https://github.com/scipy/xsf.git) registered for path 'third_party/xsf'\nCloning into '/app/repo_to_process/third_party/cccl'...\nCloning into '/app/repo_to_process/third_party/dlpack'...\nCloning into '/app/repo_to_process/third_party/jitify'...\nCloning into '/app/repo_to_process/third_party/xsf'...\n",
    "execution_time": 16.26869773864746
  },
  {
    "command": "pip install -e .",
    "success": false,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nObtaining file:///app/repo_to_process\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Checking if build backend supports build_editable: started\n  Checking if build backend supports build_editable: finished with status 'done'\n  Getting requirements to build editable: started\n  Getting requirements to build editable: finished with status 'done'\n  Preparing editable metadata (pyproject.toml): started\n  Preparing editable metadata (pyproject.toml): finished with status 'done'\nRequirement already satisfied: numpy<2.6,>=1.24 in /usr/local/lib/python3.10/dist-packages (from cupy==14.0.0a1) (2.2.6)\nCollecting fastrlock>=0.5 (from cupy==14.0.0a1)\n  Using cached https://repo.huaweicloud.com/repository/pypi/packages/15/a1/439962ed439ff6f00b7dce14927e7830e02618f26f4653424220a646cd1c/fastrlock-0.8.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_28_x86_64.whl (53 kB)\nBuilding wheels for collected packages: cupy\n  Building editable for cupy (pyproject.toml): started\n  Building editable for cupy (pyproject.toml): finished with status 'error'\nFailed to build cupy\n",
    "stderr": "  error: subprocess-exited-with-error\n  \n  × Building editable for cupy (pyproject.toml) did not run successfully.\n  │ exit code: 1\n  ╰─> [74 lines of output]\n      Clearing directory: /app/repo_to_process/cupy/.data\n      Generating CUPY_CACHE_KEY from header files...\n      CUPY_CACHE_KEY (57 files matching /app/repo_to_process/cupy/_core/include/**): c94f33edd6f6e9129f932ebfa1ed7811cfa05222\n      \n      -------- Configuring Module: cuda --------\n      cc1plus: warning: /app/repo_to_process/cupy/_core/include/cupy/_cccl/libcudacxx: not a directory\n      /tmp/tmpddc4u4qj/a.cpp:1:10: fatal error: cublas_v2.h: No such file or directory\n          1 | #include <cublas_v2.h>\n            |          ^~~~~~~~~~~~~\n      compilation terminated.\n      command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1\n      cc1plus: warning: /app/repo_to_process/cupy/_core/include/cupy/_cccl/libcudacxx: not a directory\n      /tmp/tmpsccyv825/a.cpp:2:18: fatal error: cuda_runtime_api.h: No such file or directory\n          2 |         #include <cuda_runtime_api.h>\n            |                  ^~~~~~~~~~~~~~~~~~~~\n      compilation terminated.\n      **************************************************\n      *** WARNING: Cannot check compute capability\n      command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1\n      **************************************************\n      \n      ************************************************************\n      * CuPy Configuration Summary                               *\n      ************************************************************\n      \n      Build Environment:\n        Include directories: ['/app/repo_to_process/cupy/_core/include/cupy/_cccl/libcudacxx', '/app/repo_to_process/cupy/_core/include/cupy/_cccl/thrust', '/app/repo_to_process/cupy/_core/include/cupy/_cccl/cub', '/app/repo_to_process/cupy/_core/include']\n        Library directories: []\n        nvcc command       : (not found)\n        hipcc command      : (not found)\n      \n      Environment Variables:\n        CFLAGS          : (none)\n        LDFLAGS         : (none)\n        LIBRARY_PATH    : (none)\n        CUDA_PATH       : (none)\n        NVCC            : (none)\n        HIPCC           : (none)\n        ROCM_HOME       : (none)\n      \n      Modules:\n        cuda      : No\n          -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h']\n          -> Check your CFLAGS environment variable.\n      \n      ERROR: CUDA could not be found on your system.\n      \n      HINT: You are trying to build CuPy from source, which is NOT recommended for general use.\n            Please consider using binary packages instead.\n      \n      Please refer to the Installation Guide for details:\n      https://docs.cupy.dev/en/stable/install.html\n      \n      ************************************************************\n      \n      Traceback (most recent call last):\n        File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 389, in <module>\n          main()\n        File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 373, in main\n          json_out[\"return_val\"] = hook(**hook_input[\"kwargs\"])\n        File \"/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 303, in build_editable\n          return hook(wheel_directory, config_settings, metadata_directory)\n        File \"/tmp/pip-build-env-7dxuhnoj/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py\", line 468, in build_editable\n          return self._build_with_temp_dir(\n        File \"/tmp/pip-build-env-7dxuhnoj/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py\", line 404, in _build_with_temp_dir\n          self.run_setup()\n        File \"/tmp/pip-build-env-7dxuhnoj/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py\", line 317, in run_setup\n          exec(code, locals())\n        File \"<string>\", line 61, in <module>\n        File \"/app/repo_to_process/install/cupy_builder/cupy_setup_build.py\", line 560, in get_ext_modules\n          extensions = make_extensions(ctx, compiler, use_cython)\n        File \"/app/repo_to_process/install/cupy_builder/cupy_setup_build.py\", line 405, in make_extensions\n          raise Exception('Your CUDA environment is invalid. '\n      Exception: Your CUDA environment is invalid. Please check above error log.\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\n  ERROR: Failed building editable for cupy\nerror: failed-wheel-build-for-install\n\n× Failed to build installable wheels for some pyproject.toml based projects\n╰─> cupy\n",
    "execution_time": 4.680323362350464
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "",
    "stderr": "ERROR: while parsing the following warning configuration:\n\n  error::cupy.exceptions.VisibleDeprecationWarning\n\nThis error occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py\", line 1967, in parse_warning_filter\n    category: type[Warning] = _resolve_warning_category(category_)\n  File \"/usr/local/lib/python3.10/dist-packages/_pytest/config/__init__.py\", line 2012, in _resolve_warning_category\n    m = __import__(module, None, None, [klass])\nModuleNotFoundError: No module named 'cupy'\n\n\n",
    "execution_time": 0.15865635871887207
  }
]