[
  {
    "command": "pip install -e packages/vaex-server",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nObtaining file:///app/repo_to_process/packages/vaex-server\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nRequirement already satisfied: cachetools in /usr/local/lib/python3.10/dist-packages (from vaex-server==0.9.0) (6.1.0)\nRequirement already satisfied: fastapi in /usr/local/lib/python3.10/dist-packages (from vaex-server==0.9.0) (0.116.1)\nRequirement already satisfied: tornado>4.1 in /usr/local/lib/python3.10/dist-packages (from vaex-server==0.9.0) (6.5.2)\nRequirement already satisfied: uvicorn[standard] in /usr/local/lib/python3.10/dist-packages (from vaex-server==0.9.0) (0.35.0)\nRequirement already satisfied: vaex-core~=4.7 in /usr/local/lib/python3.10/dist-packages (from vaex-server==0.9.0) (4.18.1)\nRequirement already satisfied: numpy~=1.17 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (1.26.4)\nRequirement already satisfied: aplus in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (0.11.0)\nRequirement already satisfied: tabulate>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (0.9.0)\nRequirement already satisfied: dask!=2022.4.0,<2024.9 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (2024.8.2)\nRequirement already satisfied: future>=0.15.2 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (1.0.0)\nRequirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (6.0.2)\nRequirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (1.17.0)\nRequirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (3.1.1)\nRequirement already satisfied: pandas<3,>=1.0 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (2.3.1)\nRequirement already satisfied: nest-asyncio>=1.3.3 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (1.6.0)\nRequirement already satisfied: pyarrow>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (21.0.0)\nRequirement already satisfied: frozendict!=2.2.0 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (2.4.6)\nRequirement already satisfied: blake3 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (1.0.5)\nRequirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (3.18.0)\nRequirement already satisfied: pydantic>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (2.11.7)\nRequirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.7->vaex-server==0.9.0) (14.1.0)\nRequirement already satisfied: click>=8.1 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.7->vaex-server==0.9.0) (8.2.2)\nRequirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.7->vaex-server==0.9.0) (2025.7.0)\nRequirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.7->vaex-server==0.9.0) (25.0)\nRequirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.7->vaex-server==0.9.0) (1.4.2)\nRequirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.7->vaex-server==0.9.0) (1.0.0)\nRequirement already satisfied: importlib-metadata>=4.13.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.7->vaex-server==0.9.0) (8.7.0)\nRequirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.0->vaex-core~=4.7->vaex-server==0.9.0) (2.9.0.post0)\nRequirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.0->vaex-core~=4.7->vaex-server==0.9.0) (2025.2)\nRequirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.0->vaex-core~=4.7->vaex-server==0.9.0) (2025.2)\nRequirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=4.13.0->dask!=2022.4.0,<2024.9->vaex-core~=4.7->vaex-server==0.9.0) (3.23.0)\nRequirement already satisfied: locket in /usr/local/lib/python3.10/dist-packages (from partd>=1.4.0->dask!=2022.4.0,<2024.9->vaex-core~=4.7->vaex-server==0.9.0) (1.0.0)\nRequirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.8.0->vaex-core~=4.7->vaex-server==0.9.0) (0.7.0)\nRequirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.8.0->vaex-core~=4.7->vaex-server==0.9.0) (2.33.2)\nRequirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.8.0->vaex-core~=4.7->vaex-server==0.9.0) (4.14.1)\nRequirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.8.0->vaex-core~=4.7->vaex-server==0.9.0) (0.4.1)\nRequirement already satisfied: starlette<0.48.0,>=0.40.0 in /usr/local/lib/python3.10/dist-packages (from fastapi->vaex-server==0.9.0) (0.47.2)\nRequirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.10/dist-packages (from starlette<0.48.0,>=0.40.0->fastapi->vaex-server==0.9.0) (4.10.0)\nRequirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.6.2->starlette<0.48.0,>=0.40.0->fastapi->vaex-server==0.9.0) (1.3.0)\nRequirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.6.2->starlette<0.48.0,>=0.40.0->fastapi->vaex-server==0.9.0) (3.10)\nRequirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.6.2->starlette<0.48.0,>=0.40.0->fastapi->vaex-server==0.9.0) (1.3.1)\nRequirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->vaex-core~=4.7->vaex-server==0.9.0) (3.0.0)\nRequirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->vaex-core~=4.7->vaex-server==0.9.0) (2.19.2)\nRequirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->vaex-core~=4.7->vaex-server==0.9.0) (0.1.2)\nRequirement already satisfied: h11>=0.8 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]->vaex-server==0.9.0) (0.16.0)\nRequirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]->vaex-server==0.9.0) (0.6.4)\nRequirement already satisfied: python-dotenv>=0.13 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]->vaex-server==0.9.0) (1.1.1)\nRequirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]->vaex-server==0.9.0) (0.21.0)\nRequirement already satisfied: watchfiles>=0.13 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]->vaex-server==0.9.0) (1.1.0)\nRequirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.10/dist-packages (from uvicorn[standard]->vaex-server==0.9.0) (15.0.1)\nInstalling collected packages: vaex-server\n  Attempting uninstall: vaex-server\n    Found existing installation: vaex-server 0.9.0\n    Uninstalling vaex-server-0.9.0:\n      Successfully uninstalled vaex-server-0.9.0\n  Running setup.py develop for vaex-server\nSuccessfully installed vaex-server\n",
    "stderr": "  DEPRECATION: Legacy editable install of vaex-server==0.9.0 from file:///app/repo_to_process/packages/vaex-server (setup.py develop) is deprecated. pip 25.3 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457\nWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 1.3599028587341309
  },
  {
    "command": "pip install -e packages/vaex-astro",
    "success": true,
    "stdout": "Looking in indexes: https://repo.huaweicloud.com/repository/pypi/simple/\nObtaining file:///app/repo_to_process/packages/vaex-astro\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'done'\nRequirement already satisfied: astropy in /usr/local/lib/python3.10/dist-packages (from vaex-astro==0.9.3) (6.1.7)\nRequirement already satisfied: vaex-core~=4.5 in /usr/local/lib/python3.10/dist-packages (from vaex-astro==0.9.3) (4.18.1)\nRequirement already satisfied: numpy~=1.17 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (1.26.4)\nRequirement already satisfied: aplus in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (0.11.0)\nRequirement already satisfied: tabulate>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (0.9.0)\nRequirement already satisfied: dask!=2022.4.0,<2024.9 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (2024.8.2)\nRequirement already satisfied: future>=0.15.2 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (1.0.0)\nRequirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (6.0.2)\nRequirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (1.17.0)\nRequirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (3.1.1)\nRequirement already satisfied: pandas<3,>=1.0 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (2.3.1)\nRequirement already satisfied: nest-asyncio>=1.3.3 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (1.6.0)\nRequirement already satisfied: pyarrow>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (21.0.0)\nRequirement already satisfied: frozendict!=2.2.0 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (2.4.6)\nRequirement already satisfied: blake3 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (1.0.5)\nRequirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (3.18.0)\nRequirement already satisfied: pydantic>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (2.11.7)\nRequirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from vaex-core~=4.5->vaex-astro==0.9.3) (14.1.0)\nRequirement already satisfied: click>=8.1 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.5->vaex-astro==0.9.3) (8.2.2)\nRequirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.5->vaex-astro==0.9.3) (2025.7.0)\nRequirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.5->vaex-astro==0.9.3) (25.0)\nRequirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.5->vaex-astro==0.9.3) (1.4.2)\nRequirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.5->vaex-astro==0.9.3) (1.0.0)\nRequirement already satisfied: importlib-metadata>=4.13.0 in /usr/local/lib/python3.10/dist-packages (from dask!=2022.4.0,<2024.9->vaex-core~=4.5->vaex-astro==0.9.3) (8.7.0)\nRequirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.0->vaex-core~=4.5->vaex-astro==0.9.3) (2.9.0.post0)\nRequirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.0->vaex-core~=4.5->vaex-astro==0.9.3) (2025.2)\nRequirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3,>=1.0->vaex-core~=4.5->vaex-astro==0.9.3) (2025.2)\nRequirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=4.13.0->dask!=2022.4.0,<2024.9->vaex-core~=4.5->vaex-astro==0.9.3) (3.23.0)\nRequirement already satisfied: locket in /usr/local/lib/python3.10/dist-packages (from partd>=1.4.0->dask!=2022.4.0,<2024.9->vaex-core~=4.5->vaex-astro==0.9.3) (1.0.0)\nRequirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.8.0->vaex-core~=4.5->vaex-astro==0.9.3) (0.7.0)\nRequirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.8.0->vaex-core~=4.5->vaex-astro==0.9.3) (2.33.2)\nRequirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.8.0->vaex-core~=4.5->vaex-astro==0.9.3) (4.14.1)\nRequirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.8.0->vaex-core~=4.5->vaex-astro==0.9.3) (0.4.1)\nRequirement already satisfied: pyerfa>=2.0.1.1 in /usr/local/lib/python3.10/dist-packages (from astropy->vaex-astro==0.9.3) (2.0.1.5)\nRequirement already satisfied: astropy-iers-data>=0.2024.10.28.0.34.7 in /usr/local/lib/python3.10/dist-packages (from astropy->vaex-astro==0.9.3) (0.2025.8.4.0.42.59)\nRequirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->vaex-core~=4.5->vaex-astro==0.9.3) (3.0.0)\nRequirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->vaex-core~=4.5->vaex-astro==0.9.3) (2.19.2)\nRequirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->vaex-core~=4.5->vaex-astro==0.9.3) (0.1.2)\nInstalling collected packages: vaex-astro\n  Attempting uninstall: vaex-astro\n    Found existing installation: vaex-astro 0.9.3\n    Uninstalling vaex-astro-0.9.3:\n      Successfully uninstalled vaex-astro-0.9.3\n  Running setup.py develop for vaex-astro\nSuccessfully installed vaex-astro\n",
    "stderr": "  DEPRECATION: Legacy editable install of vaex-astro==0.9.3 from file:///app/repo_to_process/packages/vaex-astro (setup.py develop) is deprecated. pip 25.3 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457\nWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\n",
    "execution_time": 1.3262765407562256
  },
  {
    "command": "pytest",
    "success": false,
    "stdout": "[08/11/25 01:40:35] ERROR    issue loading plot                  __init__.py:816\n                             Traceback (most recent call last):                 \n                               File                                             \n                             \"/usr/local/lib/python3.10/dist-pac                \n                             kages/vaex/__init__.py\", line 813,                 \n                             in <module>                                        \n                                 add_namespace = entry.load()                   \n                               File                                             \n                             \"/usr/local/lib/python3.10/dist-pac                \n                             kages/importlib_metadata/__init__.p                \n                             y\", line 221, in load                              \n                                 module =                                       \n                             import_module(self.module)                         \n                               File                                             \n                             \"/usr/lib/python3.10/importlib/__in                \n                             it__.py\", line 126, in                             \n                             import_module                                      \n                                 return                                         \n                             _bootstrap._gcd_import(name[level:]                \n                             , package, level)                                  \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1050,                 \n                             in _gcd_import                                     \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1027,                 \n                             in _find_and_load                                  \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 992,                  \n                             in _find_and_load_unlocked                         \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 241,                  \n                             in _call_with_frames_removed                       \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1050,                 \n                             in _gcd_import                                     \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1027,                 \n                             in _find_and_load                                  \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1004,                 \n                             in _find_and_load_unlocked                         \n                             ModuleNotFoundError: No module                     \n                             named 'vaex.viz'                                   \n                    ERROR    issue loading astro                 __init__.py:816\n                             Traceback (most recent call last):                 \n                               File                                             \n                             \"/usr/local/lib/python3.10/dist-pac                \n                             kages/vaex/__init__.py\", line 813,                 \n                             in <module>                                        \n                                 add_namespace = entry.load()                   \n                               File                                             \n                             \"/usr/local/lib/python3.10/dist-pac                \n                             kages/importlib_metadata/__init__.p                \n                             y\", line 221, in load                              \n                                 module =                                       \n                             import_module(self.module)                         \n                               File                                             \n                             \"/usr/lib/python3.10/importlib/__in                \n                             it__.py\", line 126, in                             \n                             import_module                                      \n                                 return                                         \n                             _bootstrap._gcd_import(name[level:]                \n                             , package, level)                                  \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1050,                 \n                             in _gcd_import                                     \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1027,                 \n                             in _find_and_load                                  \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 992,                  \n                             in _find_and_load_unlocked                         \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 241,                  \n                             in _call_with_frames_removed                       \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1050,                 \n                             in _gcd_import                                     \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1027,                 \n                             in _find_and_load                                  \n                               File \"<frozen                                    \n                             importlib._bootstrap>\", line 1004,                 \n                             in _find_and_load_unlocked                         \n                             ModuleNotFoundError: No module                     \n                             named 'vaex.astro'                                 \n",
    "stderr": "ImportError while loading conftest '/app/repo_to_process/tests/conftest.py'.\ntests/conftest.py:1: in <module>\n    from common import *\ntests/common.py:20: in <module>\n    import vaex.server.service\nE   ModuleNotFoundError: No module named 'vaex.server'\n",
    "execution_time": 1.098942756652832
  }
]